from .academics import *
from .career import *
from .course import *
from .institution import *
from .requirement import *
from .general import *
from .finance import *
from .ranking import *
from .multi_domain import *
from .user import *
